version: '3.8'

services:
  user-db:
    container_name: user-db
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT_M}:${MYSQL_PORT}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - traning-network
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - ${ZOOKEEPER_CLIENT_PORT_M}:${ZOOKEEPER_CLIENT_PORT}
    networks:
      - traning-network
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.4
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${PLAINTEXT_PORT},PLAINTEXT_HOST://localhost:${PLAINTEXT_HOST_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_JMX_PORT: ${KAFKA_JMX_PORT}
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=${KAFKA_JMX_PORT}
    ports:
      - ${PLAINTEXT_HOST_PORT_M}:${PLAINTEXT_HOST_PORT}
      - ${KAFKA_JMX_PORT_M}:${KAFKA_JMX_PORT} # metrics
    networks:
      - traning-network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: first
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:${PLAINTEXT_PORT}
      KAFKA_CLUSTERS_0_METRICS_PORT: ${KAFKA_JMX_PORT}
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:${SCHEMAREGISTRY_PORT}
    ports:
      - ${KAFKA_UI_PORT_M}:${KAFKA_UI_PORT}
    networks:
      - traning-network
  schemaregistry:
    container_name: schemaregistry
    image: confluentinc/cp-schema-registry:7.2.1
    ports:
      - ${SCHEMAREGISTRY_PORT_M}:${SCHEMAREGISTRY_PORT}
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:${PLAINTEXT_PORT}
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: http://schemaregistry:${SCHEMAREGISTRY_PORT}
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
    networks:
      - traning-network
networks:
  traning-network:
    driver: bridge